spring.application.name=ProjetoJava
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/dimdim_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:dimdim_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:SenhaSegura123!}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:none}
spring.jpa.show-sql=true